version: "3.4"

services:
  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/ppostgres/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    env_file:
      - .env
volumes:
  postgres_data: